#!/usr/bin/env python3
"""
Generate gfxpressure.vert / gfxpressure.frag: a register-hungry GRAPHICS
pipeline, so the occupancy knob is exercised on stages that have preloaded and
exported registers (which compute shaders do not), not just on compute.

Same shape as gen_pressure6.py: the body is emitted already unrolled with
literal indices, because agx_compile.c runs nir_lower_vars_to_scratch with a
256-byte threshold before loop unrolling, so a loop-indexed local array above
64 uints lands in scratch and the pressure disappears.

The vertex shader carries 8 vec4 varyings so the fragment shader has real
inputs and the vertex shader has real exports.
"""
N, S1, S2, S3 = 128, 37, 71, 113
VARYINGS = 8

vs = ["#version 450",
      "/* GENERATED by gen_gfxpressure.py -- do not edit. */"]
for v in range(VARYINGS):
    vs.append("layout(location = %d) out vec4 v%d;" % (v, v))
vs.append("void main() {")
vs.append("   /* Full-screen triangle from gl_VertexIndex, no vertex buffer. */")
vs.append("   vec2 p = vec2((gl_VertexIndex << 1) & 2, gl_VertexIndex & 2);")
vs.append("   gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);")
for v in range(VARYINGS):
    vs.append("   v%d = vec4(p.x + %d.0, p.y - %d.0, %d.5, 1.0);" % (v, v, v, v))
vs.append("}")
open("gfxpressure.vert", "w").write("\n".join(vs) + "\n")

fs = ["#version 450",
      "/* GENERATED by gen_gfxpressure.py -- do not edit. */"]
for v in range(VARYINGS):
    fs.append("layout(location = %d) in vec4 v%d;" % (v, v))
fs.append("layout(location = 0) out uint outColor;")
fs.append("layout(push_constant) uniform P { uint rounds; uint seed; } pc;")
fs.append("void main() {")
fs.append("   uint px = uint(gl_FragCoord.x);")
fs.append("   uint py = uint(gl_FragCoord.y);")
fs.append("   uint i = py * 64u + px;")
fs.append("   uint s = i * 2654435761u + pc.seed;")
for k in range(N):
    fs.append("   s = s * 1664525u + 1013904223u;")
    fs.append("   uint a%d = s ^ %uu;" % (k, (k * 0x9e3779b9) & 0xffffffff))
fs.append("   for (uint r = 0u; r < pc.rounds; ++r) {")
for k in range(N):
    y, z, w = (k + S1) % N, (k + S2) % N, (k + S3) % N
    fs.append("      { uint x = a%d + (a%d ^ (a%d + a%d));" % (k, y, z, w))
    fs.append("        x = (x << 7) | (x >> 25);")
    fs.append("        a%d = x * 2246822519u + 374761393u; }" % k)
fs.append("   }")
fs.append("   uint acc = 0u;")
for k in range(N):
    fs.append("   acc = (acc ^ a%d) * 2654435761u + %uu;" % (k, k))
fs.append("   /* Consume the varyings so they are not dead-coded, without")
fs.append("      perturbing the checkable result (they are exactly 1.0 here). */")
fs.append("   acc += uint(%s) - %uu;" % (" + ".join("v%d.w" % v for v in range(VARYINGS)), VARYINGS))
fs.append("   outColor = acc;")
fs.append("}")
open("gfxpressure.frag", "w").write("\n".join(fs) + "\n")
print("wrote gfxpressure.vert / gfxpressure.frag: N=%d strides %d/%d/%d, %d varyings"
      % (N, S1, S2, S3, VARYINGS))
