#!/usr/bin/env python3
"""
Generate pressure6.comp: a maximum-register-pressure compute shader.

Why this has to be generated rather than written by hand: agx_compile.c runs
nir_lower_vars_to_scratch with a 256-byte threshold, and it runs BEFORE loop
unrolling. Any local array indexed by a loop induction variable is therefore
put in scratch if it exceeds 64 uints, and the register count collapses
(measured: 17 GPRs, not 300). Emitting the body already unrolled with literal
indices keeps the whole array in SSA form and the pressure in registers.

The strides are odd, hence coprime with N = 128, so no slot dies early. The
round count is a push constant, so the unrolled body cannot be folded away.
"""
N, S1, S2, S3 = 128, 37, 71, 113

out = []
out.append("#version 450")
out.append("/* GENERATED by gen_pressure6.py -- do not edit. See that file for why. */")
out.append("layout(local_size_x = 32) in;")
out.append("layout(set = 0, binding = 0) buffer B { uint data[]; };")
out.append("layout(push_constant) uniform P { uint rounds; uint seed; } pc;")
out.append("void main() {")
out.append("   uint i = gl_GlobalInvocationID.x;")
out.append("   uint s = i * 2654435761u + pc.seed;")
for k in range(N):
    out.append("   s = s * 1664525u + 1013904223u;")
    out.append("   uint a%d = s ^ %uu;" % (k, (k * 0x9e3779b9) & 0xffffffff))
out.append("   for (uint r = 0u; r < pc.rounds; ++r) {")
for k in range(N):
    y, z, w = (k + S1) % N, (k + S2) % N, (k + S3) % N
    out.append("      { uint x = a%d + (a%d ^ (a%d + a%d));" % (k, y, z, w))
    out.append("        x = (x << 7) | (x >> 25);")
    out.append("        a%d = x * 2246822519u + 374761393u; }" % k)
out.append("   }")
out.append("   uint acc = 0u;")
for k in range(N):
    out.append("   acc = (acc ^ a%d) * 2654435761u + %uu;" % (k, k))
out.append("   data[i] = acc;")
out.append("}")
open("pressure6.comp", "w").write("\n".join(out) + "\n")
print("wrote pressure6.comp: N=%d strides %d/%d/%d" % (N, S1, S2, S3))
