#version 450
/* GENERATED by gen_gfxpressure.py -- do not edit. */
layout(location = 0) out vec4 v0;
layout(location = 1) out vec4 v1;
layout(location = 2) out vec4 v2;
layout(location = 3) out vec4 v3;
layout(location = 4) out vec4 v4;
layout(location = 5) out vec4 v5;
layout(location = 6) out vec4 v6;
layout(location = 7) out vec4 v7;
void main() {
   /* Full-screen triangle from gl_VertexIndex, no vertex buffer. */
   vec2 p = vec2((gl_VertexIndex << 1) & 2, gl_VertexIndex & 2);
   gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);
   v0 = vec4(p.x + 0.0, p.y - 0.0, 0.5, 1.0);
   v1 = vec4(p.x + 1.0, p.y - 1.0, 1.5, 1.0);
   v2 = vec4(p.x + 2.0, p.y - 2.0, 2.5, 1.0);
   v3 = vec4(p.x + 3.0, p.y - 3.0, 3.5, 1.0);
   v4 = vec4(p.x + 4.0, p.y - 4.0, 4.5, 1.0);
   v5 = vec4(p.x + 5.0, p.y - 5.0, 5.5, 1.0);
   v6 = vec4(p.x + 6.0, p.y - 6.0, 6.5, 1.0);
   v7 = vec4(p.x + 7.0, p.y - 7.0, 7.5, 1.0);
}
